In [1]:
import pandas as pd

# series

In [35]:
# empty series
s=pd.Series()
print(s)


Series([], dtype: object)


In [36]:
s=pd.Series(dtype='int')
print(s)

Series([], dtype: int64)


In [37]:
s=pd.Series(dtype='object')
print(s)

Series([], dtype: object)


In [38]:
s=pd.Series(dtype='float')
print(s)

Series([], dtype: float64)


In [39]:
import numpy as np
import pandas as pd

In [40]:
a=np.array(['a','b','c','d'])
s=pd.Series(a)
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [41]:
a=np.array(['a','b','c','d'])
s=pd.Series(a,index=[100,101,102,103])
print(s)

100    a
101    b
102    c
103    d
dtype: object


In [42]:
#series from dictnory
data={'a':1,'b':2,'c':3}
s=pd.Series(data)
print(s)

a    1
b    2
c    3
dtype: int64


In [43]:
data={'a':1,'b':2,'c':3}
s=pd.Series(data,index=['b','c','a','d'])# no value for d so in output it became null
print(s)

b    2.0
c    3.0
a    1.0
d    NaN
dtype: float64


In [44]:
#scalar
s=pd.Series(4,index=[1,2,3,4,5])
print(s)

1    4
2    4
3    4
4    4
5    4
dtype: int64


In [45]:
s=pd.Series(5,index=[1,2,3,4,5])
print(s)

1    5
2    5
3    5
4    5
5    5
dtype: int64


In [46]:
s=pd.Series(5,index=['a','b','c'])
print(s)

a    5
b    5
c    5
dtype: int64


In [47]:
#accessing values from series
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)
print(s[0]) #single element accessing
print()
print(s[:3])#  slicing
print()
print(s[2:]) # last value
print()
print(s[-3:])
print()
print(s['b'])
print()
print(s[['a','b','c']])  #multple element accessing


a    1
b    2
c    3
d    4
e    5
dtype: int64
1

a    1
b    2
c    3
dtype: int64

c    3
d    4
e    5
dtype: int64

c    3
d    4
e    5
dtype: int64

2

a    1
b    2
c    3
dtype: int64


C:\Users\husna\AppData\Local\Temp\ipykernel_13468\800383339.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0]) #single element accessing


# arithmetic operation

In [48]:
ser1=pd.Series([1,2,3,4],index=['USA','Germany','Italy','Japan'])
print(ser1)

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64


In [49]:
ser2=pd.Series([1,2,5,4],index=['USA','Germany','Russia','Japan'])
print(ser2)

USA        1
Germany    2
Russia     5
Japan      4
dtype: int64


In [50]:
ser1+ser2 # addition
print()
ser1-ser2 # substaction

Germany    0.0
Italy      NaN
Japan      0.0
Russia     NaN
USA        0.0
dtype: float64

# data frame

In [51]:
#  creating an empty dataframe
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [52]:
# creating a dataframe from a list
data=[1,2,3,4,5]
df=pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [55]:
# creating df from list of list
data=[['alex',10],['bob',12],['clara',13]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)

    Name  Age
0   alex   10
1    bob   12
2  clara   13


In [67]:
# df from a dictnory of a list
data={'name':['tom','jack','ricky'],
     'Age':[23,21,24]}
df=pd.DataFrame(data)
print(df)
print("shape:")
print(df.shape)# shape
print()
print("row labels:")
print(df.index)
print()
print("coloum labels:")
print(df.columns)
print()
print("datatype:")

print(df.dtypes)
print()
print("data as numpy array")
print(df.values)
print()
print("quick overview of the DataFrame’s structure.:")
print(df.info())
print()
print("statistical summary of numeric columns (by default).")
print(df.describe())



    name  Age
0    tom   23
1   jack   21
2  ricky   24
shape:
(3, 2)

row labels:
RangeIndex(start=0, stop=3, step=1)

coloum labels:
Index(['name', 'Age'], dtype='object')

datatype:
name    object
Age      int64
dtype: object

data as numpy array
[['tom' 23]
 ['jack' 21]
 ['ricky' 24]]

quick overview of the DataFrame’s structure.:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   Age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
None

statistical summary of numeric columns (by default).
             Age
count   3.000000
mean   22.666667
std     1.527525
min    21.000000
25%    22.000000
50%    23.000000
75%    23.500000
max    24.000000


In [59]:
# df from dictnory of series
d={'one':pd.Series([1,2,3],index=['a','b','c']),
  'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(d)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [69]:
d={'Name':['Anu','joe','sam','lilly'],
  'Age':[21,22,23,24],
   'Score':[58,99,87,76]
}
df=pd.DataFrame(d)
print(df)
print()
print("quick overview of the DataFrame’s structure.:")
print(df.info())
print()
print("statistical summary of numeric columns (by default).")
print(df.describe())



    Name  Age  Score
0    Anu   21     58
1    joe   22     99
2    sam   23     87
3  lilly   24     76

quick overview of the DataFrame’s structure.:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   Score   4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
None

statistical summary of numeric columns (by default).
             Age      Score
count   4.000000   4.000000
mean   22.500000  80.000000
std     1.290994  17.416467
min    21.000000  58.000000
25%    21.750000  71.500000
50%    22.500000  81.500000
75%    23.250000  90.000000
max    24.000000  99.000000


### Create a Series from a Python list.

In [70]:
li=[1,2,3,4]
s=pd.Series(li)
print(s)

0    1
1    2
2    3
3    4
dtype: int64


### Create a DataFrame from a dictionary.

In [71]:
di={'name':['alex','joe','max'],
   'Age':[21,22,23]}
df=pd.DataFrame(di)
print(df)

   name  Age
0  alex   21
1   joe   22
2   max   23


### Display DataFrame shape and column names

In [72]:
di={'name':['alex','joe','max'],
   'Age':[21,22,23]}
df=pd.DataFrame(di)
print(df)
print()
print("shape:")
print(df.shape)
print()
print("coloum names:")
print(df.columns)

   name  Age
0  alex   21
1   joe   22
2   max   23

shape:
(3, 2)

coloum names:
Index(['name', 'Age'], dtype='object')


### Create a Series of numbers 1–10.

In [73]:
a=np.arange(1,11)
s=pd.Series(a)
print(s)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


### Create a DataFrame with two columns: Name, Age.

In [74]:
data=[['joe',10],['bob',12],['clara',13]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)

    Name  Age
0    joe   10
1    bob   12
2  clara   13


### Convert a NumPy array into a DataFrame

In [76]:
a=np.array([1,2,3,4,5])
s=pd.DataFrame(a)
print(s)

   0
0  1
1  2
2  3
3  4
4  5


### Rename the columns of a DataFrame.

In [136]:
di={'name':['alex','joe','max'],
   'Age':[21,22,23]}
df=pd.DataFrame(di)
df.rename(columns={'Age':'score'},inplace=True) #one method
df




name  score
0  alex     21
1   joe     22
2   max     23

### Add a new column to a DataFrame that calculates the square of another column.


In [137]:
di={'Number':[1,2,3,4,5]}
df=pd.DataFrame(di)
print(df)
df['square']=df['Number']**2
df

   Number
0       1
1       2
2       3
3       4
4       5


Number  square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25

# extra problems

### Create a Pandas Series of 15 random integers between 1 and 50.

In [87]:
a=np.random.randint(1,50,15)
s=pd.Series(a)
print(s)

0     12
1     39
2     17
3     12
4     39
5     31
6      6
7     16
8     15
9     23
10     2
11    16
12    13
13    19
14    31
dtype: int32


### Create a Series with the first 20 even numbers.

In [88]:
a=np.arange(0,21,2)
print(a)
print()
s=pd.Series(a)
print(s)

[ 0  2  4  6  8 10 12 14 16 18 20]

0      0
1      2
2      4
3      6
4      8
5     10
6     12
7     14
8     16
9     18
10    20
dtype: int64


### Create a Series from a dictionary: {'Math': 90, 'Physics': 85, 'Chemistry': 88} and display its index and values.

In [97]:
dictionary:{'Math': 90, 'Physics': 85, 'Chemistry': 88}
s=pd.Series(dictionary)
print(s)
print()
print(s.index)
print()
print(s.values)

subject    [math, physics, chemistry]
marks                    [90, 85, 88]
dtype: object

Index(['subject', 'marks'], dtype='object')

[list(['math', 'physics', 'chemistry']) list([90, 85, 88])]


### Convert a NumPy array of size 10 with values from 0–9 into a Pandas Series.

In [104]:
a=np.arange(0,10)
print(a)
s=pd.Series(a)
print("the converted panda series is:")
print(s)

[0 1 2 3 4 5 6 7 8 9]
the converted panda series is:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


### Create a Series and select only the elements greater than 5.

In [106]:
a=np.arange(1,20)
print(a)
s=pd.Series(a)
print("the series is")
print(s)
g=s[s>5]
print("the elements greater tha 5 is")
print(g)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
the series is
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64
the elements greater tha 5 is
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64


### Create a Series and change its index to custom labels (like A, B, C, …)

In [135]:
da=[1,2,3,4]
s=pd.Series(da)
print(s)
s.index=['A','B','c','D']
s

0    1
1    2
2    3
3    4
dtype: int64


A    1
B    2
c    3
D    4
dtype: int64

### Create a DataFrame with 3 columns: Student, Math, Physics using lists.

In [134]:
student=['bob','Alice','Max','Lucas']
math_marks=[40,46,78,87]
physics_marks=[78,98,68,90]
df=pd.DataFrame({
    'student':student,
    'Maths':math_marks,
    'Pysics':physics_marks
})
df

student  Maths  Pysics
0     bob     40      78
1   Alice     46      98
2     Max     78      68
3   Lucas     87      90

### Create a DataFrame from a dictionary containing 4 students’ names and their scores in two subjects.


In [133]:
dict1={
    'student_names':['will','max','el','lucas'],
    'Mathematics':[67,86,45,56],
    'Physics':[87,57,78,65]

}
df=pd.DataFrame(dict1)
df

student_names  Mathematics  Physics
0          will           67       87
1           max           86       57
2            el           45       78
3         lucas           56       65

### Display only the first 3 rows and last 2 rows of a DataFrame.


In [132]:
age=[42,31,23,45]
name=['will','max','el','lucas']
df=pd.DataFrame({
    'age':age,
    'Name':name
})
df
c=df.head(3)
df.tail(2)
c

age  Name
0   42  will
1   31   max
2   23    el

### Select a single column and multiple columns from a DataFrame.


In [154]:
df = pd.DataFrame({
    'Name': ['Will', 'Max', 'El', 'Lucas'],
    'Age': [42, 31, 23, 45],
    'Math': [67, 86, 45, 56],
    'Physics': [87, 57, 78, 65]
})

df

Name  Age  Math  Physics
0   Will   42    67       87
1    Max   31    86       57
2     El   23    45       78
3  Lucas   45    56       65

In [155]:
co1=df[['Name']]

co1

Name
0   Will
1    Max
2     El
3  Lucas

In [156]:
mcol1=df[['Name','Age']]
mcol1

Name  Age
0   Will   42
1    Max   31
2     El   23
3  Lucas   45

### Select rows based on a condition (e.g., scores greater than 80 in Math).

In [157]:
df = pd.DataFrame({
    'Name': ['Will', 'Max', 'El', 'Lucas'],
    'Age': [42, 31, 23, 45],
    'Math': [67, 86, 45, 56],
    'Physics': [87, 57, 78, 65]
})

df

Name  Age  Math  Physics
0   Will   42    67       87
1    Max   31    86       57
2     El   23    45       78
3  Lucas   45    56       65

In [161]:
a=df[df['Math']>80]
a

Name  Age  Math  Physics
1  Max   31    86       57

### Add a new column Total that sums up the scores of Math and Physics.

In [162]:
df = pd.DataFrame({
    'Name': ['Will', 'Max', 'El', 'Lucas'],
    'Age': [42, 31, 23, 45],
    'Math': [67, 86, 45, 56],
    'Physics': [87, 57, 78, 65]
})

df

Name  Age  Math  Physics
0   Will   42    67       87
1    Max   31    86       57
2     El   23    45       78
3  Lucas   45    56       65

In [173]:
df['total']=df['Math']+df['Physics']

df

Name  Age  Math  Physics  total
0   Will   42    67       87    154
1    Max   31    86       57    143
2     El   23    45       78    123
3  Lucas   45    56       65    121

### Rename the columns Math → Mathematics, Physics → PhysicsScore.

In [174]:
df = pd.DataFrame({
    'Name': ['Will', 'Max', 'El', 'Lucas'],
    'Age': [42, 31, 23, 45],
    'Math': [67, 86, 45, 56],
    'Physics': [87, 57, 78, 65]
})

df

Name  Age  Math  Physics
0   Will   42    67       87
1    Max   31    86       57
2     El   23    45       78
3  Lucas   45    56       65

In [180]:
c=df.rename(columns={'Math':'Mathematics','Physics':'physicsscore'})
c

Name  Age  Mathematics  physicsscore
0   Will   42           67            87
1    Max   31           86            57
2     El   23           45            78
3  Lucas   45           56            65

### Drop a column from a DataFrame.


In [181]:
df = pd.DataFrame({
    'Name': ['Will', 'Max', 'El', 'Lucas'],
    'Age': [42, 31, 23, 45],
    'Math': [67, 86, 45, 56],
    'Physics': [87, 57, 78, 65]
})

df

Name  Age  Math  Physics
0   Will   42    67       87
1    Max   31    86       57
2     El   23    45       78
3  Lucas   45    56       65

In [190]:
c=df.drop(columns='Age')
c

Name  Math  Physics
0   Will    67       87
1    Max    86       57
2     El    45       78
3  Lucas    56       65

### Create a DataFrame from a NumPy array of shape (5,3) and assign custom column names.



In [197]:
a=np.arange(1,16).reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [199]:
df=pd.DataFrame(a, columns=['Column1', 'Column2', 'Column3'])
df

Column1  Column2  Column3
0        1        2        3
1        4        5        6
2        7        8        9
3       10       11       12
4       13       14       15

### Sort the DataFrame by a column in ascending and descending order.

In [201]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Math': [85, 90, 78, 92],
    'Physics': [92, 88, 80, 95]
}

df = pd.DataFrame(data)
df

Name  Math  Physics
0    Alice    85       92
1      Bob    90       88
2  Charlie    78       80
3    David    92       95

In [205]:
asort=df.sort_values(by='Math',ascending=True)
asort

Name  Math  Physics
2  Charlie    78       80
0    Alice    85       92
1      Bob    90       88
3    David    92       95

In [208]:
dsort=df.sort_values(by='Math',ascending=False)
dsort

Name  Math  Physics
3    David    92       95
1      Bob    90       88
0    Alice    85       92
2  Charlie    78       80

In [217]:
a=np.arange(30,42).reshape(3,4)
df=pd.DataFrame(a, columns=['a', 'b', 'c','d'])
df


a   b   c   d
0  30  31  32  33
1  34  35  36  37
2  38  39  40  41

In [219]:
new=df.rename(columns={'a':'Maths','b':'Chemistry','c':'physics','d':'biology'})
new

Maths  Chemistry  physics  biology
0     30         31       32       33
1     34         35       36       37
2     38         39       40       41

In [224]:
new['total']=df.sum(axis=1)
new

Maths  Chemistry  physics  biology  total
0     30         31       32       33    126
1     34         35       36       37    142
2     38         39       40       41    158